### ISSUE TITLE
Login Errors - has the keep API changed?

### ISSUE THREAD

**Issue by nmeyne** [djsudduth/keep-it-markdown#47]
On Ubuntu 22.04.1 LTS I have python3 and pip 22.3 and kim seemingly installed OK, but I can't get a successful keep-test to run: Technical Error Message: LoginException('BadAuthentication', None)
I have tried logging in to keep in both chrome and firefox browsers, but I'm still getting the authentication error. Does this method support 2FA on the Google account? Wondering if there have been any other changes?  Sorry if I have missed something - kim looks great.

**Comment by ichmoimeyo** [comment]
I am using KIM online @ replit.com ... so none of the following may be relevant to you ...

**1st** login issue I had was solved by following the instructions ...

> If you believe you typed in your Google account name and password correctly and it failed, copy and paste or click on this URL (https://accounts.google.com/DisplayUnlockCaptcha) into your browswer address bar and approve the request by pressing the 'Continue' button.

**2nd** login issue was solved by ...

pip3 install --upgrade keyrings.alt

... that I described here [How I solved my keyring sign-in issue #37](https://github.com/djsudduth/keep-it-markdown/issues/37)

... then everything worked fine for ever and ever less a day ...

**3rd** login issue when I started using 2 Step verification on my phone ...

Solved by using [Sign in with App Passwords](https://support.google.com/accounts/answer/185833?hl=en)

**Comment by djsudduth** [comment]
Thank you @ichmoimeyo for the helpful response. Also, @nmeyne you must use Python 3.8+. There were some changes in the libraries that broke 3.7.

**Comment by nmeyne** [comment]
Many thanks @ichmoimeyo and @djsudduth.  Yes I have tried all 3 methods above, but I'm still getting the same error.  What app name should be used for sign in with app passwords?

**Comment by djsudduth** [comment]
You can use any name you want - it is just a identifiable name for you. Be sure to log out of any and all Google accounts and use the first 2FA app password with KIM. If you use it with the KIM teat app you'll need another app pw. @nmeyne

**Comment by nmeyne** [comment]
@djsudduth yes all that done multiple times now in keep-test and KIM, but I am still getting the 'BadAuthentication' for keep-test auth and for KIM Username or password is incorrect (LoginException('BadAuthentication'))  Could not excute KIM.  Must be something else or local. Might try replit as @ichmoimeyo had success there.

**Comment by ichmoimeyo** [comment]
@nmeyne I made myself a myNotes.txt cheat-sheet in replit to go through as well as copy commands from to paste into the console. At the time I created the apppassword due to 2 Step verification I copied it so that I could easily reuse it whenever needed.

Here is my cheat-sheet - hopefully not too confusing ...

/////////////////////////////////////////

pip install -r requirements.txt

pip3 install --upgrade keyrings.alt

python keep-test.py

Enter your Google account username: XYXYXY

Enter your Google Password: apppassword NOT actual google acct password

Test worked!! You've succesfully logged into Google Keep! Please try running Keep-it-Markdown or KIM!

python kim.py

Welcome to Keep it Markdown or KIM!

FIRST TIME ///////

Enter your Google account username: XYXYXY

Enter your Google Password: apppassword

One moment...

Please set a password for your new keyring: 

Please confirm the password: 

You've succesfully logged into Google Keep! Your Keep access token has been securely stored in this computer's keyring.

Enter a keyword search, label search or '--all' to convert Keep notes to md or '--x' to exit:

end FIRST TIME ///////

SECOND TIME ///

Enter your Google account username: XYXYXY

Please enter password for encrypted keyring: 1234

You've succesfully logged into Google Keep using local keyring access token!

Enter a keyword search, label search or '--all' to convert Keep notes to md or '--x' to exit:

end SECOND TIME ///

/////////////////////////////////////////

**Comment by ichmoimeyo** [comment]
@nmeyne Glad it worked for you - the pip3 always worked for me but I've edited the cheat-sheet for anybody reading this in the future. 

https://www.pythonpool.com/pip-vs-pip3/

**Comment by djsudduth** [comment]
Glad you solved it @nmeyne and thanks again @ichmoimeyo !!
